services:
  backend:
    image: image-reg-here/strava-history-backend:latest
    pull_policy: always
    ports:
      - '4000:4000'
    secrets:
      - source: backend_env
        target: /app/.env

  frontend:
    image: image-reg-here/strava-history-frontend:latest
    pull_policy: always
    env_file:
      - ./frontend.env
    ports:
      - '5173:5173'
    depends_on:
      - backend

secrets:
  backend_env:
    file: ./backend.env
